name: digit
dependencies:
    - python=3.13  # Tested with 3.13.5 but other versions should work
    - pip  # Install pip 
    - pip:  # Include pip dependencies last
        - digit-interface  # Official DIGIT Python interface
