name: digit
dependencies:
    - python=3.12 # Tested with 3.12 but other versions should work
    - pip # Install pip 
    - pip: # Include pip dependencies last
        - digit-interface # Official DIGIT Python interface
